---

- name: get instance information
  action: ec2_facts

- name: tag instance
  ec2_tag: resource={{ ansible_ec2_instance_id }} region={{ ansible_ec2_placement_region }}
  args:
    tags:
      "version:{{ edx_notes_api_service_name }}" : "{{ edx_notes_api_source_repo }} {{ edx_notes_api_code_checkout.after |truncate(7,True,'')}}"
  when: edx_notes_api_code_checkout.after is defined
